### ISSUE TITLE
Datum za Tijelovo nije ispravan

### ISSUE THREAD

**Issue by salk52** [IvanVnucec/neradni-dani-u-hr#2]
Datum za Tijelovo nije fiksan već se isto računa, kaže wiki "deveti četvrtak nakon Uskrsa"

**Comment by IvanVnucec** [comment]
popravljeno u [c8a4d27](https://github.com/IvanVnucec/neradni-dani-u-hr/commit/c8a4d27389e3a792953ba3e1b1a293eb2c51a441).
Hvala!
